name: movies
description: This is project in clean archtecture.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  logger: ^1.3.0
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  lint: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/config/
